openapi: "3.0.0"
info:
  title: Customer OAS
  description: Customer endpoints
  version: "1.0"
servers:
  - url: http://localhost:3000
    description: Development server
  - url: http://localhost:8080
    description: Reverse Proxy server    
paths:
  /customer/{custId}:
    get:
      description: Get customer record by customer id
      operationId: findCustomerByCustomerId
      parameters:
      - name: custId
        in: path
        schema:
         type: number
         format: int32
         minimum: 100
        required: true
      responses:
        '200':
          description: Return customer record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /customers:
    get:
      description: Get list of customers
      operationId: getCustomers
      parameters:
      - name: offset
        in: query
        schema:
         type: number
         format: int32
        required: false
      - name: limit
        in: query
        schema:
         type: number
         format: int32
        required: false        
      responses:
        '200':
          description: A paged array of customer
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Customer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                
  /customer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '201':
          description: New customer added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerAdded"

components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: number
          format: int32
        name:
          type: string
        email:
          type: string 
          format: email   
      required:
      - name
      - email           
    CustomerAdded:
      type: object
      properties:
        customerId:
          type: number
          format: int32
          minimum: 100
        message:
          type: string
        time:
          type: string
      required:
      - customerId
      - message
      - time                    
    Error:
      type: object    
      properties:
        message:
          type: string
      required:
      - message        


